import type * as tslib from "typescript/lib/tsserverlibrary";
import type { InlineSchema, PluginConfig, SchemaColumn, SchemaTable } from "./types.js";

/**
 * Load schema tables from plugin config.
 *
 * Supports two sources (both can be present; schemaFile wins on conflict):
 *  1. Inline `config.schema` — immediate JSON in tsconfig.json plugins array
 *  2. `config.schemaFile` — path to a file generated by `pnpm pull`
 */
export function loadSchema(
  config: PluginConfig,
  projectRoot: string,
  ts: typeof tslib,
  readFile: (path: string) => string | undefined,
  log: (msg: string) => void,
): SchemaTable[] {
  const tables = new Map<string, SchemaTable>();

  // ── 1. Inline schema from tsconfig.json ──────────────────────────────────
  if (config.schema) {
    for (const [tableName, columns] of Object.entries(config.schema as InlineSchema)) {
      tables.set(tableName, {
        name: tableName,
        columns: Object.entries(columns).map(([name, type]) => ({ name, type })),
      });
    }
  }

  // ── 2. Generated db-types.ts file ────────────────────────────────────────
  if (config.schemaFile) {
    const absPath = config.schemaFile.startsWith("/")
      ? config.schemaFile
      : `${projectRoot}/${config.schemaFile.replace(/^\.\//, "")}`;

    const source = readFile(absPath);
    if (!source) {
      log(`schemaFile not found: ${absPath}`);
    } else {
      const parsed = parseSchemaFile(source, ts, log);
      for (const table of parsed) {
        tables.set(table.name, table);
      }
    }
  }

  return [...tables.values()];
}

/**
 * Parse a db-types.ts file (produced by `pnpm pull`) and extract table info.
 *
 * Looks for:
 *   export type Tables = { users: UsersRow; posts: PostsRow; ... }
 *   export interface UsersRow { id: number; name: string; ... }
 */
function parseSchemaFile(
  source: string,
  ts: typeof tslib,
  log: (msg: string) => void,
): SchemaTable[] {
  const sf = ts.createSourceFile("db-types.ts", source, ts.ScriptTarget.Latest, true);

  // Collect all interface members keyed by interface name
  const interfaces = new Map<string, SchemaColumn[]>();
  // Table name -> interface name (from Tables type alias)
  const tableToInterface = new Map<string, string>();

  for (const stmt of sf.statements) {
    // export interface UsersRow { ... }
    if (
      ts.isInterfaceDeclaration(stmt) &&
      hasExportModifier(ts, stmt)
    ) {
      const ifName = stmt.name.text;
      const columns: SchemaColumn[] = [];
      for (const member of stmt.members) {
        if (ts.isPropertySignature(member) && member.name) {
          const colName = member.name.getText(sf);
          const colType = member.type ? member.type.getText(sf) : "unknown";
          columns.push({ name: colName, type: colType });
        }
      }
      interfaces.set(ifName, columns);
    }

    // export type Tables = { users: UsersRow; posts: PostsRow; }
    if (
      ts.isTypeAliasDeclaration(stmt) &&
      hasExportModifier(ts, stmt) &&
      stmt.name.text === "Tables" &&
      ts.isTypeLiteralNode(stmt.type)
    ) {
      for (const member of stmt.type.members) {
        if (ts.isPropertySignature(member) && member.name && member.type) {
          const tableName = member.name.getText(sf).replace(/['"]/g, "");
          const ifaceName = member.type.getText(sf).trim();
          tableToInterface.set(tableName, ifaceName);
        }
      }
    }
  }

  if (tableToInterface.size === 0) {
    log("parseSchemaFile: no Tables type alias found — falling back to interface names");
    // Fallback: treat every *Row interface as a table
    for (const [ifName, columns] of interfaces) {
      if (ifName.endsWith("Row")) {
        const tableName = toSnakeCase(ifName.slice(0, -3));
        tableToInterface.set(tableName, ifName);
      }
    }
  }

  const result: SchemaTable[] = [];
  for (const [tableName, ifaceName] of tableToInterface) {
    const columns = interfaces.get(ifaceName) ?? [];
    result.push({ name: tableName, columns });
  }
  return result;
}

function hasExportModifier(ts: typeof tslib, node: tslib.Node): boolean {
  return (
    (ts.getCombinedModifierFlags(node as tslib.Declaration) & ts.ModifierFlags.Export) !== 0
  );
}

function toSnakeCase(s: string): string {
  return s
    .replace(/([A-Z])/g, "_$1")
    .toLowerCase()
    .replace(/^_/, "");
}
