/** A column extracted from the schema. */
export interface SchemaColumn {
  name: string;
  /** TypeScript type string as it appears in the generated interface, e.g. "string | null" */
  type: string;
}

/** A table extracted from the schema. */
export interface SchemaTable {
  name: string;
  columns: SchemaColumn[];
}

/** Inline schema definition accepted in tsconfig.json plugins config. */
export type InlineSchema = Record<string, Record<string, string>>;

/**
 * Plugin configuration accepted as the second element of the plugins array in
 * tsconfig.json:
 *
 * ```json
 * {
 *   "compilerOptions": {
 *     "plugins": [{
 *       "name": "@playwright-labs/ts-plugin-sql",
 *       "tag": "sql",
 *       "schemaFile": "./src/db-types.ts"
 *     }]
 *   }
 * }
 * ```
 */
export interface PluginConfig {
  /**
   * Name of the tagged template tag to enhance (default: "sql").
   * Set to another value if you alias the tag, e.g. `"pgSql"`.
   */
  tag?: string;

  /**
   * Path (relative to tsconfig.json) to the file generated by `pnpm pull`.
   * The loader reads `export interface *Row` definitions and `export type Tables`.
   */
  schemaFile?: string;

  /**
   * Inline schema when you don't have a generated file.
   * Keys are table names; values are `{ columnName: "tsType" }` maps.
   *
   * @example
   * ```json
   * { "users": { "id": "number", "name": "string", "email": "string | null" } }
   * ```
   */
  schema?: InlineSchema;
}
