/**
 * Database row types for the example project.
 *
 * In a real project this file would be generated by running:
 *   pnpm --filter @playwright-labs/fixture-sql pull -a sqlite -u ./example.db -o src/db-types.ts
 */

export interface UsersRow {
  id: number;
  name: string;
  email: string;
  created_at: string;
}

export interface PostsRow {
  id: number;
  user_id: number;
  title: string;
  body: string;
  published: boolean;
  created_at: string;
}

export interface CommentsRow {
  id: number;
  post_id: number;
  user_id: number;
  text: string;
  created_at: string;
}

/** Maps table names to their row interfaces — used by @playwright-labs/ts-plugin-sql */
export type Tables = {
  users: UsersRow;
  posts: PostsRow;
  comments: CommentsRow;
};
