packages:
  - packages/*
  - examples/reporter-email
  - examples/reporter-otel
  - examples/sql
  - examples/ghost-cursor
  - '!packages/playwright-best-practices'
  - '!packages/playwright-best-practices-build'

onlyBuiltDependencies:
  - better-sqlite3
  - cpu-features
  - esbuild
  - nice-napi
  - protobufjs
  - ssh2

savePrefix: ''
