/**
 * Shared email primitives for the `@playwright-labs/fixture-*` email packages
 * (`fixture-gmail`, `fixture-mailpit`, ...).
 *
 * A provider implements {@link EmailProviderAPI} — usually by extending
 * {@link EmailProvider}, which adds the polling {@link EmailProvider.waitForEmail}
 * and {@link EmailProvider.getEmailLinks} helpers on top of the raw
 * `findEmail` / `readEmail` / `markAsRead` operations.
 */

import EventEmitter from "node:events";
import { Readable } from "node:stream";

/** A single email summary returned by `findEmail`. */
export interface Email {
  /** Provider message id — pass it to `readEmail` / `getEmailLinks` / `markAsRead`. */
  id: string;
  subject?: string;
  from?: string;
  to?: string;
  /** Date string as reported by the provider. */
  date?: string;
  /** Short plain-text snippet generated by the provider. */
  snippet: string;
  /** read email text as readable stream */
  readAsStream(): Readable;
  /** read email text as buffer */
  readAsBytes(): Promise<Buffer>;
  /** read email text as string */
  readAsString(): Promise<string>;
}

/** Options for `findEmail`. */
export type FindEmailOptions = {
  /**
   * Subject filter. A string is matched by the provider's server-side search
   * query, a `RegExp` is applied client-side to the subject.
   */
  subject?: string | RegExp;
  /** Sender filter. String -> provider query, `RegExp` -> client-side. */
  from?: string | RegExp;
  /** Recipient filter. String -> provider query, `RegExp` -> client-side. */
  to?: string | RegExp;
  /** Raw provider search query, appended to the generated query. */
  query?: string;
  /** Only unread messages. */
  unread?: boolean;
  /** Maximum number of messages to inspect. @default 10 */
  limit?: number;
};

/** Options for `readEmail`. */
export type ReadEmailOptions = {
  /**
   * Which body part to prefer.
   * Falls back to the other format when the preferred one is absent.
   * @default "html"
   */
  format?: "html" | "text";
};

/** Options for {@link EmailProvider.waitForEmail}. */
export type WaitForEmailOptions = FindEmailOptions & {
  /** Maximum time to wait for a matching email, in milliseconds. @default 30000 */
  timeout?: number;
  /** Polling interval, in milliseconds. @default 1000 */
  interval?: number;
};

/**
 * The operations every email provider exposes.
 *
 * `findEmail()` without filters lists the whole mailbox (newest first).
 */
export interface EmailProviderAPI {
  /**
   * Find emails in the mailbox.
   *
   * String filters are translated into the provider's server-side search
   * query, `RegExp` filters are applied client-side (see {@link filterEmails}).
   * Called without options it lists the whole mailbox.
   *
   * @returns matching emails (newest first, up to `limit`) or `null` when nothing matches.
   * @example
   * ```ts
   * const emails = await provider.findEmail({ subject: /qwe/, unread: true });
   * ```
   */
  findEmail(options?: FindEmailOptions): Promise<Email[] | null>;

  /**
   * Read the body of an email by its id (see {@link findEmail}).
   *
   * @returns the email body — HTML by default, plain text when
   * `format: "text"` or when the message has no HTML part.
   */
  readEmail(emailId: string, options?: ReadEmailOptions): Promise<string>;

  /**
   * Mark an email as read.
   */
  markAsRead(emailId: string): Promise<void>;

  /**
   * Poll {@link findEmail} until at least one email matches or the timeout
   * elapses.
   *
   * @returns the newest matching email.
   * @throws when no email matches within `timeout` (default 30s).
   */
  waitForEmail(options?: WaitForEmailOptions): Promise<Email>;

  /**
   * Extract all unique links (`href` values) from an email's HTML body.
   */
  getEmailLinks(emailId: string): Promise<string[]>;
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

/**
 * Extract all unique links (`href` values) from an HTML document,
 * in order of first appearance.
 */
export function extractLinks(html: string): string[] {
  const links = new Set<string>();
  for (const match of html.matchAll(/href\s*=\s*["']([^"']*)["']/gi)) {
    if (match[1]) {
      links.add(match[1]);
    }
  }
  return [...links];
}

/**
 * Apply the client-side `RegExp` filters of {@link FindEmailOptions}
 * (`subject` / `from` / `to`) to already-fetched emails.
 * String filters are expected to be handled by the provider's search query.
 */
export function filterEmails<T extends Email>(
  emails: T[],
  options: Pick<FindEmailOptions, "subject" | "from" | "to">,
): T[] {
  const { subject, from, to } = options;
  return emails.filter((email) => {
    if (subject instanceof RegExp && !subject.test(email.subject ?? "")) {
      return false;
    }
    if (from instanceof RegExp && !from.test(email.from ?? "")) {
      return false;
    }
    if (to instanceof RegExp && !to.test(email.to ?? "")) {
      return false;
    }
    return true;
  });
}

/** The bound `readAs*` methods of an {@link Email}. */
export type EmailReaders = Pick<Email, "readAsStream" | "readAsBytes" | "readAsString">;

/**
 * Create the {@link Email} `readAs*` methods on top of a `readEmail`-style
 * callback. Providers spread the result into every email they return:
 *
 * ```ts
 * {
 *   id: message.ID,
 *   subject: message.Subject,
 *   ...emailReaders((options) => this.readEmail(message.ID, options)),
 * }
 * ```
 *
 * All readers fetch the body lazily on every call; `readAsStream` pulls it
 * as a single-chunk `Readable`.
 */
export function emailReaders(
  read: (options?: ReadEmailOptions) => Promise<string>,
): EmailReaders {
  return {
    readAsStream: () =>
      Readable.from(
        (async function* () {
          yield await read();
        })(),
      ),
    readAsBytes: async () => Buffer.from(await read(), "utf-8"),
    readAsString: () => read(),
  };
}

/** Payload of the `"email.send"` event. */
export type EmailSendEvent = {
  to: string | string[];
  cc?: string | string[];
  bcc?: string | string[];
  subject: string;
  /** Message id assigned by the provider (when available). */
  id?: string;
};

/** Payload of the `"email.read"` event. */
export type EmailReadEvent = {
  /** Id of the email that was read. */
  id: string;
  /** Decoded body that was returned. */
  body: string;
};

/**
 * Events emitted by {@link EmailProvider}:
 * - `"email.send"` — an email was sent via the provider's `sendEmail`.
 * - `"email.receive"` — {@link EmailProvider.waitForEmail} matched an incoming email.
 * - `"email.read"` — an email body was read via `readEmail`.
 * - `"email.find"` — `findEmail` returned at least one match.
 */
export type EmailProviderEvents = {
  "email.send": [email: EmailSendEvent];
  "email.receive": [email: Email];
  "email.read": [email: EmailReadEvent];
  "email.find": [emails: Email[]];
};
/**
 * Base class for email provider clients.
 *
 * Implements {@link waitForEmail} (polling) and {@link getEmailLinks}
 * (HTML link extraction) on top of the abstract `findEmail` / `readEmail`.
 *
 * Emits the {@link EmailProviderEvents} events. The abstract methods are
 * implemented by concrete providers, which are responsible for emitting
 * `"email.find"` / `"email.read"` / `"email.send"` from their
 * `findEmail` / `readEmail` / `sendEmail` implementations;
 * `"email.receive"` is emitted by {@link waitForEmail} itself.
 *
 * The generic parameter lets providers return an extended {@link Email} shape:
 * ```ts
 * type GmailEmail = Email & { threadId: string };
 * class Gmail extends EmailProvider<GmailEmail> { ... }
 * ```
 */
export abstract class EmailProvider<T extends Email = Email>
  extends EventEmitter<EmailProviderEvents>
  implements EmailProviderAPI
{
  /**
   * Find emails in the mailbox.
   *
   * String filters are translated into the provider's server-side search
   * query, `RegExp` filters are applied client-side (see {@link filterEmails}).
   * Called without options it lists the whole mailbox.
   *
   * @returns matching emails (newest first, up to `limit`) or `null` when nothing matches.
   */
  abstract findEmail(options?: FindEmailOptions): Promise<T[] | null>;

  /**
   * Read the body of an email by its id (see {@link findEmail}).
   *
   * @returns the email body — HTML by default, plain text when
   * `format: "text"` or when the message has no HTML part.
   */
  abstract readEmail(
    emailId: string,
    options?: ReadEmailOptions,
  ): Promise<string>;

  /**
   * Mark an email as read.
   */
  abstract markAsRead(emailId: string): Promise<void>;

  /**
   * Poll {@link findEmail} until at least one email matches or the timeout
   * elapses. Useful right after an action that triggers an email
   * (sign up, password reset, ...).
   *
   * Emits the `"email.receive"` event when a matching email is found.
   *
   * @returns the newest matching email.
   * @throws when no email matches within `timeout` (default 30s).
   * @example
   * ```ts
   * const email = await mailpit.waitForEmail({ to: user.email, subject: /verify/i });
   * ```
   */
  async waitForEmail(options: WaitForEmailOptions = {}): Promise<T> {
    const { timeout = 30_000, interval = 1_000, ...find } = options;
    const deadline = Date.now() + timeout;
    for (;;) {
      const emails = await this.findEmail(find);
      if (emails?.length) {
        this.emit("email.receive", emails[0]!);
        return emails[0]!;
      }
      const remaining = deadline - Date.now();
      if (remaining <= 0) {
        throw new Error(
          `email-core: no email matched within ${timeout}ms (query: ${JSON.stringify(find)})`,
        );
      }
      await sleep(Math.min(interval, remaining));
    }
  }

  /**
   * Extract all unique links (`href` values) from an email's HTML body.
   * The email is read via `readEmail`.
   *
   * @example
   * ```ts
   * const [confirmUrl] = await mailpit.getEmailLinks(email.id);
   * await page.goto(confirmUrl!);
   * ```
   */
  async getEmailLinks(emailId: string): Promise<string[]> {
    const body = await this.readEmail(emailId, { format: "html" });
    return extractLinks(body);
  }
}
