export {
  a,
  body,
  br,
  div,
  type Email as BaseEmail,
  EmailProvider,
  type EmailProviderAPI,
  extractLinks,
  filterEmails,
  type FindEmailOptions,
  fragment,
  h,
  h1,
  h2,
  h3,
  h4,
  h5,
  h6,
  head,
  hr,
  html,
  img,
  li,
  p,
  type ReadEmailOptions,
  table,
  tbody,
  td,
  th,
  thead,
  title,
  tr,
  ul,
  type WaitForEmailOptions,
} from "@playwright-labs/email-core";
export { expect, type Fixture, test } from "./fixture";
export {
  type Email,
  Mailpit,
  type MailpitAttachment,
  type MailpitOptions,
  type SendEmailOptions,
  type SendEmailResult,
} from "@playwright-labs/email-core/providers/mailpit";
