export {
  createCursor,
  getElementBox,
  getRandomPagePoint,
  installMouseHelper,
  path,
  GhostCursor,
  type BoundingBox,
  type BoxOptions,
  type ClickOptions,
  type CreateCursorOptions,
  type DefaultOptions,
  type GetElementOptions,
  type MouseButton,
  type MouseButtonOptions,
  type MoveOptions,
  type MoveToOptions,
  type PathOptions,
  type RandomMoveOptions,
  type ScrollIntoViewOptions,
  type ScrollOptions,
  type ScrollToDestination,
} from "./cursor";

export {
  add,
  bezierCurve,
  bezierCurveSpeed,
  clamp,
  direction,
  div,
  extrapolate,
  generateBezierAnchors,
  magnitude,
  mult,
  origin,
  overshoot,
  perpendicular,
  randomNumberRange,
  randomVectorOnLine,
  scale,
  setMagnitude,
  sub,
  unit,
  type TimedVector,
  type Vector,
} from "./math";
