export { expect, test, type Fixture, type UseWebAuthn } from "./fixture.js";
export {
  WebAuthn,
  VirtualAuthenticator,
  VirtualAuthenticatorArray,
  matchesCredentialFilter,
  isCredential,
  type AuthenticatorProtocol,
  type AuthenticatorTransport,
  type Credential,
  type CredentialAddedEvent,
  type CredentialAssertedEvent,
  type CredentialDeletedEvent,
  type CredentialExport,
  type CredentialFilter,
  type CredentialProperties,
  type CredentialUpdatedEvent,
  type Ctap2Version,
  type EnableOptions,
  type ResponseOverrideBits,
  type VirtualAuthenticatorOptions,
  type WaitForEventOptions,
} from "@playwright-labs/webauthn";
